import type { Metadata } from "next";
// import localFont from 'next/font/local';
import "./globals.css";
import NavSideBar from "../components/NavSideBar"; 
import Header from "../components/Header";

// Keep font configuration
// const sfPro = localFont({
//   src: 'SF Pro', 
//   variable: '--font-sf-pro',
//   display: 'swap'
// });

// Keep metadata
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Update the function signature and component rendering
export default function RootLayout({
  children,
}: Readonly<{ // Keep Readonly type from your original file
  children: React.ReactNode;
}>) {
   return (
    <html lang="en">
      <body className={`antialiased font-sans`}>
        <div className={`fixed top-0 left-0 h-screen z-30 w-64`}>
          <NavSideBar />
        </div>
        <div className={`flex flex-col flex-1 min-h-screen ml-64`}>
          <div className={`fixed top-0 left-64 right-0 z-20 bg-white shadow h-20`}>
                <Header />
          </div>
          <main className={`flex-1 p-6 bg-gray-100 mt-18 overflow-y-auto`}> 
            {children}
          </main>
          </div>
      </body>
    </html>
  );
}